### ISSUE TITLE
lab

### ISSUE THREAD

**Issue by Jamofl** [yinfredyue/CMU-15213-Lab#2]

**Comment by Jamofl** [comment]
do you have the original lab code files? I'm just a passer by, I  don't have ucb account, but I want to try some labs, thx!

**Comment by yinfredyue** [comment]
Check this out (this link is in README): http://csapp.cs.cmu.edu/3e/labs.html

**Comment by Jamofl** [comment]
> Check this out (this link is in README): http://csapp.cs.cmu.edu/3e/labs.html

yes, I checked it, but it's sad that we need a CSAPP account to get the tar file, but I am not a ubc student. Is there other way to get it? thanks!

**Comment by Jamofl** [comment]
> Check this out (this link is in README): http://csapp.cs.cmu.edu/3e/labs.html

solved! many thx!
